server {
    server_name 149.28.21.68.sslip.io;

    location /api/ {
        proxy_pass http://localhost:8080;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type' always;
        if ($request_method = OPTIONS) {
            return 204;
        }
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/149.28.21.68.sslip.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/149.28.21.68.sslip.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = 149.28.21.68.sslip.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name 149.28.21.68.sslip.io;
    return 404; # managed by Certbot
}
